### ISSUE TITLE
Avalanche Explorer lists variable assets as fixed assets on the Fuji testnet

### ISSUE THREAD

**Issue by tanselkaya** [ava-labs/avalanche-explorer#107]
https://explorer.avax-test.network/asset/2FXXaU9dLG7cfudq3FVmhJtq3mBpzv44YxBwzbosoFXjmz9Ert

**Comment by kadir96** [comment]
It looks like the api returns asset as variableCap, but since the `nft` and `variableCap` fields from response are mapped to `TransactionResponse` and `Transaction` the assets' type is default to fixed cap. Will create a PR tomorrow

**Comment by strictlymomo** [comment]
Thanks for flagging this. 

Changes ended up being a bit different to your PR and are captured here: https://github.com/ava-labs/avalanche-explorer/pull/121
