### ISSUE TITLE
Wrong balance

### ISSUE THREAD

**Issue by ekherit** [ava-labs/avalanche-explorer#21]
There is a wrong balance on address 
https://explorer.ava.network/address/BZUz5nMxahio79tzdxnYKsV3uS8o1gXDn
comparing with balance got from my node and from https://bootstrap.ava.network:21000

Moreover last transaction is shown 3 days ago while I am sending  transactions every minute.

**Comment by strictlymomo** [comment]
Thanks. This issue spans two parts of the Explorer stack.

- The balance discrepancy is being investigated on the [backend](https://github.com/ava-labs/ortelius). 
- We fixed the query to get an address's most recent transactions. The frontend data will reflect the most recent transactions processed by our backend.

Will keep this open until the balance is resolved.

**Comment by ekherit** [comment]
Thank you!
Now balance at receiving address BZUz5nMxahio79tzdxnYKsV3uS8o1gXDn is OK (delay is view transactions), 
but sending address X-CsEZoWbBXLqCmjt8gdLSFyHKxCZw8gQQx is  wrong. Now my node answer me balance
is 70645, but explorer shows 127536
