### ISSUE TITLE
Only two digits after floating point

### ISSUE THREAD

**Issue by ekherit** [ava-labs/avalanche-explorer#32]
There are only 2 digits after floating point for transaction  at Latest transaction section at main page and Transaction section at an address page. This result in additional request to explorer  and increase server load.
![tmp](https://user-images.githubusercontent.com/2533826/87242643-d18bfd00-c458-11ea-8277-6566f44c322e.png)

**Comment by ekherit** [comment]
It should be 9 digits.

**Comment by strictlymomo** [comment]
Resolved in #33.
