### ISSUE TITLE
C-chain link in Explorer 

### ISSUE THREAD

**Issue by slideloft** [ava-labs/avalanche-explorer#38]
Hi guys.
I noticed in the Nav of the explorer https://explorer.avax.network that the link to the C-chain was not properly linked. 

When user click the C-CHAIN link it directs them to https://explorer.avax.network/http:/cchain.avaexplorer.com/ instead of https:/cchain.avaexplorer.com/ directly.
it also seems http://cchain.avaexplorer.com/ is not online or not working.

**Comment by strictlymomo** [comment]
http://cchain.avaexplorer.com/ is back online. Nav links fixed in #41
