### ISSUE TITLE
A 400 status error viewing a staking transaction.

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanche-explorer#57]
![Screenshot from 2020-08-22 22-10-18](https://user-images.githubusercontent.com/6778681/90969238-4a548f00-e4c4-11ea-8eec-9e96aeb613f7.png)

https://explorer.avax.network/address/X-everest1fw9msk6vs7xwu94uqc654uddrrtvsmw53ynu2x

Go to the transaction for a staking node and then click on the address for that node.

This 400 should not happen.

**Comment by strictlymomo** [comment]
@tyler-smith Ortelius will need to support P-chain tx to support the proposed solution.
