### ISSUE TITLE
Page 1 of 0 in pagination on bottom of page

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanche-explorer#58]
![Screenshot from 2020-08-22 22-12-35](https://user-images.githubusercontent.com/6778681/90969268-9bfd1980-e4c4-11ea-8df0-0a2749274ff5.png)

https://explorer.avax.network/address/X-everest1fw9msk6vs7xwu94uqc654uddrrtvsmw53ynu2x

**Comment by aaronbuchwald** [comment]
It looks like this is impacting the active validators page at the moment: 
<img width="1122" alt="Screen Shot 2020-09-28 at 11 29 41 AM" src="https://user-images.githubusercontent.com/24684335/94452795-e9cd0780-017d-11eb-886d-b6eb49c8f833.png">
