### ISSUE TITLE
Explorer front end does not show To field correctly in main page

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/avalanche-explorer#79]
The explorer front end does not render the To field for transactions in the main page as transactions are coming in. However, when. I click on the txID for more details, the to addresses are there as normal.

<img width="1115" alt="Screen Shot 2020-09-30 at 7 06 19 PM" src="https://user-images.githubusercontent.com/24684335/94748747-0751cb00-0350-11eb-96da-8362882d1756.png">

**Comment by elitedev1314520** [comment]
I would like to help with issues.
Is there anyone I can chat with?
